Numpy Applications include:
    
    1. Plotting for Matplotlib
    2. Backend (Pandas)
    3. Machine Learning 

In [1]:
import numpy as np

In [15]:
a = np.array([1,2,3])

print(a)

[1 2 3]


The above shows the creation of a 1 dimnensional array 


In [7]:
b = np.array([[1,2,3],[4,5,6]])

print (b)

[[1 2 3]
 [4 5 6]]


In [8]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0,]])

print (b)

[[1. 2. 3.]
 [4. 5. 6.]]


Notice that values within the arrays can be integers or floats

The above shows the creation of a 2 dimensional array 

a 2 dimensional arraycreated is essentially a matrix

Notice that the array only accpets lists as a data structure, hence the nested list syntax used for the 2 dimensional array 

In [9]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

A_dimension = a.ndim
B_dimension = b.ndim

print(A_dimension)
print(B_dimension)

1
2


ndim number of dimensions 

The above shows how to check the dimesnsion of arrays 

This is done using the n.dim method on the array object

In [10]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

A_shape = a.shape
B_shape = b.shape

print(A_shape)
print(B_shape)

(3,)
(2, 3)


The above shows the use of shape. 

Shape is supposed to give the rows and columns but this depends whether the array is 1 dimensional or 2 dimensional:

For a 1D array, the shape would be (n,) where n is the number of elements in your array.

For a 2D array, the shape would be (n,m) where n is the number of rows and m is the number of columns in your array.

## --------------------

## Accessing/Changing specific elements,rows,columns etc

## 1. Specific values

In [25]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

print(a[0,0])
print(a[1,1])
print(a[2,0])

1
8


IndexError: index 2 is out of bounds for axis 0 with size 2

Note that even before retriving any specific value within the matrix, the length of lists/number of values within the list has to be of the same size for the matrix to be valid/complete

The retriving runs by index numbers, with 0 as the first index

## 2. Specific Rows/Columns

In [28]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

selected_row = a [ 0, : ]

print (selected_row)

[1 2 3 4 5 6]


The anove syntax of a [ 0, : ] is refering to the index 0 for the 1st row, and the : represents selecting all rows. 

The inverse syntax is true for selecting specific columns

In [114]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

selected_column = a [ :, 0 ]

print (a)
print ('blank space')
print (selected_column)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
blank space
[1 7]


The follwing shows how to obtain segments of either the specific row or specific column

In [31]:
A = np.array([[1,2,3,4,5,6,7],[7,8,9,10,11,12,13]])

segment_of_1st_row = A [0, 1:5:2]
print(segment_of_1st_row)

[2 4]


In [32]:
A = np.array([[1,2,3,4,5,6,7],[7,8,9,10,11,12,13]])

segment_of_1st_row = A [0, 1:6:2]
print(segment_of_1st_row)

[2 4 6]


Recall that for stepping/intervals, the index of the end value of the series is non inclusive. 

A.k.a: Observe the different in the [2 4] and [2  4  6] outcomes 

In [45]:
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

print(B)

segment_of_1st_column = B [0:5:, 0]
print ("----")
print(segment_of_1st_column)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
----
[ 1  4  7 10 13]


Observe again that the end of the indexing is not inclusive so eg. 0:5: means that the 0th to 4th row is being selected, with no step intervals

## 2.1 Specific Rows/Columns changing of values

In [46]:
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

B[:,1] = [0]

print(B)

[[ 1  0  3]
 [ 4  0  6]
 [ 7  0  9]
 [10  0 12]
 [13  0 15]
 [16  0 18]]


In [49]:
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

B[:,1] = [0,9,8,7,6,5]

print(B)

[[ 1  0  3]
 [ 4  9  6]
 [ 7  8  9]
 [10  7 12]
 [13  6 15]
 [16  5 18]]


## ! Conditional selection (more on this concept in pandas)

In [112]:
A = np.array([1,2,3,4,5,6,7,8,9,10,11])

boolean_array = A > 4

print(A[boolean_array])

[ 5  6  7  8  9 10 11]


the boolean_array here is holding a set of results that are the matrice values, and it is later placed into the orginal matrix A as the new set of values thorugh (A [boolean_array] )

The boolean_array = A > 4 here represents the condition 

# intializing/creating/re-recreating matricies (zeros/full methods)

In [51]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [117]:
np.zeros((2,3),dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [118]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [116]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [55]:
np.full((2,2),"10")

array([['10', '10'],
       ['10', '10']], dtype='<U2')

In [56]:
np.full((3,3),"A")

array([['A', 'A', 'A'],
       ['A', 'A', 'A'],
       ['A', 'A', 'A']], dtype='<U1')

In [57]:
x = np.arange(6, dtype=np.int)
np.full_like(x, 1)


array([1, 1, 1, 1, 1, 1])

In [58]:
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
np.full_like(B, 100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

The full_like method is referencing to the shape of a list that has been created earlier 

as comapred to the full only method where the shape of the matrix has to be defined


# intializing/creating/re-recreating matricies (random methods)

For random decimal values:

In [60]:
np.random.rand(4,2)

array([[0.40442602, 0.61929656],
       [0.82571943, 0.19739901],
       [0.73830937, 0.89734846],
       [0.99049625, 0.82270118]])

The shape of the matrix has to be defined when using the np.random.rand method 

In [122]:
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

print(f"B.shape = {B.shape}")

np.random.random_sample (B.shape)

B.shape = (6, 3)


array([[0.166964  , 0.40350664, 0.64354495],
       [0.8682619 , 0.77571146, 0.23363376],
       [0.40529944, 0.6412175 , 0.09733021],
       [0.93398576, 0.35607804, 0.19564592],
       [0.28953914, 0.17386726, 0.63057932],
       [0.6761496 , 0.18498619, 0.53903603]])

The np.random.random_sample can be used when there is already an earlier defined list, and when the objective is to replace exsiting values within that list with random decimal values

For random interger values:

In [63]:
np.random.randint(0,10, size=(3,3))

array([[9, 0, 1],
       [7, 3, 4],
       [8, 8, 6]])

In [64]:
np.random.randint(-10,5, size=(3,3))

array([[ -4,   2,  -4],
       [ -3,   2,  -4],
       [  2,  -8, -10]])

Notice the difference for random interger values as compared to random decimal values, is that the range of interger values to be specificed, followed by the size specification

Whereas for random decimal values, only the size specificatoin was needed

# intializing/creating/re-recreating matricies (identity martix)

In [65]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [125]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Np.identity(n) to created an indentity matrix, where n referes to both the number of rows and columns desired

# intializing/creating/re-recreating matricies (creating through repeating)

In [77]:
arr = np.array ([[1,2,3],[4,5,6]])

r1 = np.repeat(arr,3,axis=0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [78]:
arr = np.array ([[1,2,3],[4,5,6]])

r1 = np.repeat(arr,3,axis=1)

print(r1)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


Observe from the above examples that the axis of 0 and 1 is referrring to the rows, and columns , respectively

The axis order follows the conventional : 1.row, then column for matrices

# Matrix Math



Math (Basic Operatros) 

In [79]:
a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [80]:
a + 2 

array([3, 4, 5, 6])

In [81]:
a - 2 

array([-1,  0,  1,  2])

In [82]:
a * 2

array([2, 4, 6, 8])

In [83]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [84]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

Math (Statistics)



In [94]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
np.min(stats)

1

In [89]:
np.max(stats)

6

In [90]:
np.min(stats,axis=1)

array([1, 4])

In [93]:
np.max(stats,axis=1)

array([3, 6])

In [96]:
stats = np.array([[1,2,3,88,99],[4,5,6,22,33]])
stats

array([[ 1,  2,  3, 88, 99],
       [ 4,  5,  6, 22, 33]])

In [97]:
np.max(stats,axis=1)

array([99, 33])

In [101]:
arr = np.array([[1,2,3],[4,5,6]])
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

Math (Usings the arrays to manipulate themselves)

In [102]:
arr = np.array([[1,2,3],[4,5,6]])
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [99]:
arr = np.array([[1,2,3],[4,5,6]])
stats * stats

array([[ 1,  4,  9],
       [16, 25, 36]])

In [100]:
stats = np.array([[1,2,3],[4,5,6]])
stats / stats

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
arr = np.array([[1,4,9],[25,36,49]])
np.sqrt(arr)

array([[1., 2., 3.],
       [5., 6., 7.]])